- name: Update SSH Pub Keys
  hosts: debian
  tasks:
    - name: fetch all public ssh keys
      delegate_to: localhost
      shell: cat ssh-pub-key.pub
      register: ssh_keys
      tags:
        - ssh

    - name: check keys
      debug: msg="{{ ssh_keys.stdout }}"
      tags:
        - ssh

    - name: deploy keys on all servers
      authorized_key: user="{{ user }}" key="{{ item[0] }}"
      delegate_to: "{{ item[1] }}"
      with_nested:
        - "{{ ssh_keys.stdout }}"
        - "{{groups['debian']}}"
      tags:
        - ssh